// import { Metadata } from "next"
// import "styles/globals.css"


// import { headers } from 'next/headers'

// // import { cookieToInitialState } from 'wagmi'

// // import { config } from '@lib/config'
// import {AppKit} from '@lib/context'

// const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://localhost:8000"

// export const metadata: Metadata = {
//   metadataBase: new URL(BASE_URL),
//   title: 'LuxuryVerse',
//   description: 'Generated by create next app'
// }

// export default function RootLayout({
//   children
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   const initialState = cookieToInitialState(config, headers().get('cookie'))
//   return (
//     <Web3ModalProvider initialState={initialState}>
//     <html lang="en">
//       <body>
//       {children}
//       </body>
//     </html>
//     </Web3ModalProvider>
//   )
// }


// export const metadata: Metadata = {
//   metadataBase: new URL(BASE_URL),
// }
// interface RootLayoutProps {
//   children: React.ReactNode;
// }
// export default function RootLayout({ children }: RootLayoutProps) {

  
//   // const initialState = cookieToInitialState(headers().get('cookie'))
//   return (
//     <html lang="en" data-mode="dark">

    
//       <body>
//       <AppKit>
//         <main className="relative">{children}</main>
//         </AppKit>
//       </body>
 

//     </html>
//   )
// }

// const isDev = process.env.NODE_ENV === 'development'

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" data-mode="dark" suppressHydrationWarning={isDev}>
//       <head>
//         <meta name="description" content="LuxuryVerse" />
//         <link rel="icon" href="/favicon.png" sizes="any" />
//         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700&family=Plus+Jakarta+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" />
//       </head>
//       <body suppressHydrationWarning={true}>
//       <AppKit>
//         <main className="relative">{children}</main>
//         </AppKit>
//         </body>
//     </html>
//   );
// }
import { Metadata } from "next"
import "styles/globals.css"
import { headers } from 'next/headers'
import {AppKit} from '@lib/context'
import { Outfit, Plus_Jakarta_Sans } from 'next/font/google'
const outfit = Outfit({ subsets: ['latin'] })
const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://localhost:8000"

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: 'LuxuryVerse',
  description: 'LuxuryVerse is a luxury marketplace for the metaverse.'
}

const isDev = process.env.NODE_ENV === 'development'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mode="dark" suppressHydrationWarning={isDev} className={`${outfit.className} ${plusJakartaSans.className}`}>
      <head>
        <meta name="description" content="LuxuryVerse" />
        <link rel="icon" href="/favicon.png" sizes="any" />
        <script src="https://kit.fontawesome.com/4db0bda51a.js" crossOrigin="anonymous" async></script>
      </head>
      <body suppressHydrationWarning={true}>
        <AppKit>
          <main className="relative">{children}</main>
        </AppKit>
      </body>
    </html>
  );
}